{
 "title": "ASP.NET Core | System overview",
 "description": "Basic measurements of request handling using data from prometheus-net middleware",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "services",
    "label": "Services",
    "query": "label_values(http_server_request_duration_seconds_count, service_name)"
   },
   {
    "name": "routes",
    "label": "Endpoints",
    "query": "label_values(http_server_request_duration_seconds_count, http_route)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cpu percentage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(dotnet_process_cpu_time_seconds_total[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "Error rate by endpoint",
   "type": "timeseries",
   "description": "4xx and 5xx status codes",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name =~ \"$services\", http_route =~ \"$routes\", http_response_status_code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[$__rate_interval])) by (controller, code)",
     "legendFormat": "{{http_route}}"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name =~ \"$services\", http_response_status_code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[$__rate_interval])) by ( code)"
    }
   ]
  },
  {
   "title": "Request duration (server-handled requests only)",
   "type": "heatmap",
   "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_bucket{service_name =~ \"$services\", http_route =~ \"$routes\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total memory in bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "dotnet_process_memory_working_set_bytes"
    }
   ]
  },
  {
   "title": "Total req/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name =~ \"$services\", http_route =~ \"$routes\"}[3m]))"
    }
   ]
  },
  {
   "title": "In progress (global)",
   "type": "stat",
   "description": "Across ALL controllers globally!",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{service_name =~ \"$services\"})"
    }
   ]
  },
  {
   "title": "All requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count[$__rate_interval])*60"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "dotnet_gc_last_collection_heap_size_bytes"
    }
   ]
  },
  {
   "title": "Current http connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 10 },
   "targets": [
    { "expr": "kestrel_active_connections" }
   ]
  },
  {
   "title": "Average request duration / per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": " sum by (http_route) (increase(http_server_request_duration_seconds_bucket{}[$__rate_interval])) "
    }
   ]
  },
  {
   "title": "Requests received by endpoint",
   "type": "timeseries",
   "description": "Counts all requests, both successful and failed",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name =~ \"$services\", http_route =~ \"$routes\"}[3m])) by (http_route)",
     "legendFormat": "{{http_route}}"
    }
   ]
  }
 ]
}