using DotNet.ServiceName.Application.DTOs;
using DotNet.ServiceName.Application.Models;
using Facet.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Xunit;

namespace DotNet.ServiceName.Application.Tests.Mappings;

/// <summary>
/// Tests to validate the mapping between data models and DTOs generated by Facet.
/// </summary>
public sealed class MappingTests
{
    [Fact]
    public void StatusResponse_ShouldMapToDto_WithNestedAppInfo()
    {
        var source = new StatusResponse
        {
            Created = new DateTime(2026, 1, 1, 12, 0, 0, DateTimeKind.Utc),
            AppInfo = new AppInfo
            {
                MachineName = "test-machine",
                EnvironmentName = "Development",
                HostingEnvironmentName = "Development",
                ReleaseDate = new DateTime(2025, 6, 15, 9, 30, 0, DateTimeKind.Utc),
                AppStartTime = new DateTime(2026, 1, 1, 11, 45, 0, DateTimeKind.Utc),
                Version = "1.2.3",
                Runtime = ".NET 10.0.1"
            }
        };

        var dto = source.ToFacet<StatusResponse, StatusResponseDto>();

        Assert.Equal(source.Created, dto.Created);
        Assert.NotNull(dto.AppInfo);
        Assert.Equal(source.AppInfo.MachineName, dto.AppInfo.MachineName);
        Assert.Equal(source.AppInfo.EnvironmentName, dto.AppInfo.EnvironmentName);
        Assert.Equal(source.AppInfo.HostingEnvironmentName, dto.AppInfo.HostingEnvironmentName);
        Assert.Equal(source.AppInfo.ReleaseDate, dto.AppInfo.ReleaseDate);
        Assert.Equal(source.AppInfo.AppStartTime, dto.AppInfo.AppStartTime);
        Assert.Equal(source.AppInfo.Version, dto.AppInfo.Version);
        Assert.Equal(source.AppInfo.Runtime, dto.AppInfo.Runtime);
    }

    [Fact]
    public void StatusResponse_ShouldMapToDto_WithNullAppInfo()
    {
        var source = new StatusResponse
        {
            Created = new DateTime(2026, 1, 1, 12, 0, 0, DateTimeKind.Utc),
            AppInfo = null
        };

        var dto = source.ToFacet<StatusResponse, StatusResponseDto>();

        Assert.Equal(source.Created, dto.Created);
        Assert.Null(dto.AppInfo);
    }

    [Theory]
    [InlineData(typeof(StatusResponse), typeof(StatusResponseDto))]
    [InlineData(typeof(AppInfo), typeof(AppInfoDto))]
    public void Dto_ShouldContainAllFields_FromModel(Type modelType, Type dtoType)
    {
        var modelProperties = GetPropertyNames(modelType);
        var dtoProperties = GetPropertyNames(dtoType);

        // all fields from the model must be converted into the DTO - no fields lost during mapping
        Assert.Subset(new HashSet<string>(dtoProperties), new HashSet<string>(modelProperties));
    }

    private static IEnumerable<string> GetPropertyNames(Type type)
    {
        return type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Select(property => property.Name)
            .OrderBy(name => name);
    }
}
