using DotNet.ServiceName.Application.DTOs;
using DotNet.ServiceName.Application.Models;
using Facet.Extensions;
using Xunit;

namespace DotNet.ServiceName.Application.Tests.Mappings;

/// <summary>
/// Tests to validate the mapping between data models and DTOs generated by Facet.
/// </summary>
public sealed class MappingTests
{
    [Fact]
    public void StatusResponse_ShouldMapToDto_WithNestedAppInfo()
    {
        var source = new StatusResponse
        {
            Created = new DateTime(2026, 1, 1, 12, 0, 0, DateTimeKind.Utc),
            AppInfo = new AppInfo
            {
                MachineName = "test-machine",
                EnvironmentName = "Development",
                ReleaseDate = new DateTime(2025, 6, 15, 9, 30, 0, DateTimeKind.Utc),
                AppStartTime = new DateTime(2026, 1, 1, 11, 45, 0, DateTimeKind.Utc),
                Version = "1.2.3"
            }
        };

        var dto = source.ToFacet<StatusResponse, StatusResponseDto>();

        Assert.Equal(source.Created, dto.Created);
        Assert.NotNull(dto.AppInfo);
        Assert.Equal(source.AppInfo.MachineName, dto.AppInfo.MachineName);
        Assert.Equal(source.AppInfo.EnvironmentName, dto.AppInfo.EnvironmentName);
        Assert.Equal(source.AppInfo.ReleaseDate, dto.AppInfo.ReleaseDate);
        Assert.Equal(source.AppInfo.AppStartTime, dto.AppInfo.AppStartTime);
        Assert.Equal(source.AppInfo.Version, dto.AppInfo.Version);
    }

    [Fact]
    public void StatusResponse_ShouldMapToDto_WithNullAppInfo()
    {
        var source = new StatusResponse
        {
            Created = new DateTime(2026, 1, 1, 12, 0, 0, DateTimeKind.Utc),
            AppInfo = null
        };

        var dto = source.ToFacet<StatusResponse, StatusResponseDto>();

        Assert.Equal(source.Created, dto.Created);
        Assert.Null(dto.AppInfo);
    }
}