using DotNet.ServiceName.Api.Infrastructure.Swagger;
using DotNet.ServiceName.Common.Extensions;
using HealthChecks.UI.Client;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using Microsoft.Extensions.Logging;
using Scalar.AspNetCore;

namespace DotNet.ServiceName.Api.Infrastructure.Extensions;

/// <summary>
/// Extensions for endpoint router builder.
/// </summary>
public static class EndpointRouteBuilderExtensions
{
    /// <summary>
    /// Adds the Scalar API reference UI as an alternative to Swagger UI.
    /// It reuses the same versioned OpenAPI documents generated by Swashbuckle.
    /// </summary>
    /// <remarks>
    /// More details here: https://scalar.com/
    /// </remarks>
    public static void AddScalarApiReferenceEndpoint(this IEndpointRouteBuilder endpoints, IConfiguration configuration)
    {
        // serve the API reference at /scalar with a document selector for each discovered API version
        endpoints.MapScalarApiReference(options =>
        {
            options
                .WithTitle($"{Constants.ApiName} - Scalar")
                .WithOpenApiRoutePattern("/swagger/{documentName}/swagger.json");

            if (configuration.IsSwaggerAuthEnabled())
            {
                // add support for the API Key authorization to be able to call secured endpoints from Scalar
                options.AddApiKeySupport();
            }
        });
    }

    public static void AddHealthcheckEndpoints(this IEndpointRouteBuilder endpoints,
        Common.Configuration.HealthCheckOptions? healthCheckConfig)
    {
        if (healthCheckConfig is { HealthCheckUiEnabled: true })
        {
            var environment = endpoints.ServiceProvider.GetRequiredService<IWebHostEnvironment>();
            var logger = endpoints.ServiceProvider.GetRequiredService<ILoggerFactory>().CreateLogger(
                typeof(EndpointRouteBuilderExtensions));

            // add Health Check UI
            endpoints.MapHealthChecksUI(config =>
            {
                config.UIPath = "/healthcheck-dashboard";
                config.PageTitle = healthCheckConfig.HeaderText;

                // the dashboard is a packaged single page application - it only accepts a custom
                // stylesheet as a physical file, so resolve the configured wwwroot relative path
                if (!string.IsNullOrWhiteSpace(healthCheckConfig.CustomStylesheet))
                {
                    var stylesheet = environment.WebRootFileProvider.GetFileInfo(healthCheckConfig.CustomStylesheet);
                    if (stylesheet.Exists && !string.IsNullOrEmpty(stylesheet.PhysicalPath))
                    {
                        config.AddCustomStylesheet(stylesheet.PhysicalPath);
                    }
                    else
                    {
                        logger.LogWarning(
                            "Custom health check dashboard stylesheet '{Stylesheet}' was not found in wwwroot - dashboard defaults are used",
                            healthCheckConfig.CustomStylesheet);
                    }
                }
            });
        }

        // add HealthCheck simple endpoint - only
        endpoints.MapHealthChecks("/healthcheck", new HealthCheckOptions
        {
            Predicate = (check) => check.Tags.Contains("ready")
        }).DisableRateLimiting();

        // all health checks here with details
        endpoints.MapHealthChecks("/health", new HealthCheckOptions
        {
            Predicate = _ => true,
            ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
        }).DisableRateLimiting();

        // add custom health checks
        // Readiness endpoint
        endpoints.MapHealthChecks("/health/ready", new HealthCheckOptions
        {
            ResultStatusCodes =
            {
                [HealthStatus.Healthy] = StatusCodes.Status200OK,
                [HealthStatus.Degraded] = StatusCodes.Status500InternalServerError,
                [HealthStatus.Unhealthy] = StatusCodes.Status503ServiceUnavailable
            },
            Predicate = (check) => check.Tags.Contains("ready"),
            ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse,
            AllowCachingResponses = false
        }).DisableRateLimiting();

        // Liveness endpoint
        endpoints.MapHealthChecks("/health/live", new HealthCheckOptions
        {
            Predicate = (check) => !check.Tags.Contains("ready"),
            ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse,
            AllowCachingResponses = false
        }).DisableRateLimiting();
    }
}